"""workspace enhancement models

Revision ID: 4a3dc4f00e0a
Revises: 7907dafdd076
Create Date: 2026-06-04 15:20:31.776934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3dc4f00e0a'
down_revision: Union[str, Sequence[str], None] = '7907dafdd076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_custom', sa.Boolean(), nullable=True))
    op.add_column('categories', sa.Column('author_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_categories_author_id'), 'categories', ['author_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.add_column('knowledge_wiki', sa.Column('source_file_name', sa.String(), nullable=True))
    op.add_column('knowledge_wiki', sa.Column('custom_prompt_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_wiki', 'custom_prompt_used')
    op.drop_column('knowledge_wiki', 'source_file_name')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_author_id'), table_name='categories')
    op.drop_column('categories', 'author_id')
    op.drop_column('categories', 'is_custom')
    # ### end Alembic commands ###
