"""Initial migration

Revision ID: 6bf941f8a922
Revises: 
Create Date: 2026-06-01 00:06:14.410907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf941f8a922'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('custom_prompt', sa.String(), nullable=True))
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.drop_constraint(op.f('categories_parent_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_wiki', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='wikistatus'), nullable=True))
    op.create_index(op.f('ix_knowledge_wiki_author_id'), 'knowledge_wiki', ['author_id'], unique=False)
    op.create_index(op.f('ix_knowledge_wiki_category_id'), 'knowledge_wiki', ['category_id'], unique=False)
    op.create_index('ix_knowledge_wiki_embedding_hnsw', 'knowledge_wiki', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_knowledge_wiki_status'), 'knowledge_wiki', ['status'], unique=False)
    op.drop_constraint(op.f('knowledge_wiki_category_id_fkey'), 'knowledge_wiki', type_='foreignkey')
    op.drop_constraint(op.f('knowledge_wiki_author_id_fkey'), 'knowledge_wiki', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_wiki', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'knowledge_wiki', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_wiki', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_wiki', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_wiki_author_id_fkey'), 'knowledge_wiki', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('knowledge_wiki_category_id_fkey'), 'knowledge_wiki', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_knowledge_wiki_status'), table_name='knowledge_wiki')
    op.drop_index('ix_knowledge_wiki_embedding_hnsw', table_name='knowledge_wiki', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_knowledge_wiki_category_id'), table_name='knowledge_wiki')
    op.drop_index(op.f('ix_knowledge_wiki_author_id'), table_name='knowledge_wiki')
    op.drop_column('knowledge_wiki', 'status')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_parent_id_fkey'), 'categories', 'categories', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_column('categories', 'custom_prompt')
    # ### end Alembic commands ###
