"""Add description to Category

Revision ID: f080ea1f2c18
Revises: 6e19e5eb2333
Create Date: 2026-06-02 10:18:08.168048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f080ea1f2c18'
down_revision: Union[str, Sequence[str], None] = '6e19e5eb2333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
